# Generated by Django 3.1 on 2020-10-22 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0003_subreddit_avatar'),
        ('posts', '0002_auto_20200921_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subreddit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_posts', to='subreddits.subreddit'),
        ),
    ]
