# Generated by Django 3.1 on 2020-10-24 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201022_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
