# Generated by Django 3.1 on 2020-10-07 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_votes_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='votes_total',
        ),
    ]
