# Generated by Django 3.1 on 2020-09-17 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
