# Generated by Django 3.1 on 2020-09-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0002_subreddit_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
